parameters:
#    vae_user.example.class: Vae\UserBundle\Example

services:
#    vae_user.example:
#        class: %vae_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
