admin_agendas_create:
    pattern:  /create
    defaults: { _controller: "VaeAdminBundle:Agendas:create" }

admin_agendas_update:
    pattern:  /{id}/update
    defaults: { _controller: "VaeAdminBundle:Agendas:update" }

admin_agendas_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "VaeAdminBundle:Agendas:delete" }


admin_agendas_index:
    pattern: /{page}
    defaults: 
        _controller: "VaeAdminBundle:Agendas:index"
        page: 1
    requirements:
        page: \d+

admin_agendas_index_add:
    pattern: /add/page_{page}
    defaults: 
        _controller: "VaeAdminBundle:Agendas:index_add"
        page: 1
    requirements:
        page: \d+

admin_agendas_index_update:
    pattern: /update_{id}/page_{page}
    defaults: 
        _controller: "VaeAdminBundle:Agendas:index_update"
        page: 1
    requirements:
        page: \d+
        id: \d+
