admin_contacts_create:
    pattern:  /create
    defaults: { _controller: "VaeAdminBundle:Contacts:create" }

admin_contacts_update:
    pattern:  /{id}/update
    defaults: { _controller: "VaeAdminBundle:Contacts:update" }

admin_contacts_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "VaeAdminBundle:Contacts:delete" }


admin_contacts_index:
    pattern: /{page}
    defaults: 
        _controller: "VaeAdminBundle:Contacts:index"
        page: 1
    requirements:
        page: \d+

admin_contacts_index_add:
    pattern: /add/page_{page}
    defaults: 
        _controller: "VaeAdminBundle:Contacts:index_add"
        page: 1
    requirements:
        page: \d+

admin_contacts_index_update:
    pattern: /update_{id}/page_{page}
    defaults: 
        _controller: "VaeAdminBundle:Contacts:index_update"
        page: 1
    requirements:
        page: \d+
        id: \d+
