admin_formations_create:
    pattern:  /create
    defaults: { _controller: "VaeAdminBundle:Formations:create" }

admin_formations_update:
    pattern:  /{id}/update
    defaults: { _controller: "VaeAdminBundle:Formations:update" }

admin_formations_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "VaeAdminBundle:Formations:delete" }


admin_formations_index:
    pattern: /{page}
    defaults: 
        _controller: "VaeAdminBundle:Formations:index"
        page: 1
    requirements:
        page: \d+

admin_formations_index_add:
    pattern: /add/page_{page}
    defaults: 
        _controller: "VaeAdminBundle:Formations:index_add"
        page: 1
    requirements:
        page: \d+

admin_formations_index_update:
    pattern: /update_{id}/page_{page}
    defaults: 
        _controller: "VaeAdminBundle:Formations:index_update"
        page: 1
    requirements:
        page: \d+
        id: \d+
