admin_rubriques_create:
    pattern:  /create
    defaults: { _controller: "VaeAdminBundle:Rubriques:create" }

admin_rubriques_update:
    pattern:  /{id}/update
    defaults: { _controller: "VaeAdminBundle:Rubriques:update" }

admin_rubriques_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "VaeAdminBundle:Rubriques:delete" }


admin_rubriques_index:
    pattern: /{page}
    defaults: 
        _controller: "VaeAdminBundle:Rubriques:index"
        page: 1
    requirements:
        page: \d+

admin_rubriques_index_add:
    pattern: /add/page_{page}
    defaults: 
        _controller: "VaeAdminBundle:Rubriques:index_add"
        page: 1
    requirements:
        page: \d+

admin_rubriques_index_update:
    pattern: /update_{id}/page_{page}
    defaults: 
        _controller: "VaeAdminBundle:Rubriques:index_update"
        page: 1
    requirements:
        page: \d+
        id: \d+
