admin_users_create:
    pattern:  /create
    defaults: { _controller: "VaeAdminBundle:Users:create" }

admin_users_update:
    pattern:  /{id}/update
    defaults: { _controller: "VaeAdminBundle:Users:update" }

admin_users_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "VaeAdminBundle:Users:delete" }


admin_users_index:
    pattern: /{page}
    defaults: 
        _controller: "VaeAdminBundle:Users:index"
        page: 1
    requirements:
        page: \d+

admin_users_index_add:
    pattern: /add/page_{page}
    defaults: 
        _controller: "VaeAdminBundle:Users:index_add"
        page: 1
    requirements:
        page: \d+

admin_users_index_update:
    pattern: /update_{id}/page_{page}
    defaults: 
        _controller: "VaeAdminBundle:Users:index_update"
        page: 1
    requirements:
        page: \d+
        id: \d+
