vae_base_agenda_agenda:
    pattern:  /{_locale}/{nomSite}/agenda
    defaults: { _controller: VaeBaseBundle:Agenda:agenda , _locale: fr }
    requirements:
        _locale:  fr|en
        
vae_base_dons_dons:
    pattern:  /{_locale}/{nomSite}/dons
    defaults: { _controller: VaeBaseBundle:Dons:dons , _locale: fr }
    requirements:
        _locale:  fr|en
        
vae_base_rubrique_detail:
    pattern:  /{_locale}/{nomSite}/{slugRubrique}
    defaults: { _controller: VaeBaseBundle:Rubrique:detail , _locale: fr }
    requirements:
        _locale:  fr|en

vae_base_agenda_detail:
    pattern:  /{_locale}/{nomSite}/{slugAgenda}/
    defaults: { _controller: VaeBaseBundle:Agenda:detail , _locale: fr }
    requirements:
        _locale:  fr|en
        
vae_base_formation_contact_send:
    pattern:  /{_locale}/{nomSite}/{slugRubrique}/send
    defaults: { _controller: VaeBaseBundle:Contact:form , _locale: fr }
    requirements:
        _locale:  fr|en
        
vae_base_formation_detail:
    pattern:  /{_locale}/{nomSite}/{slugRubrique}/{slugFormation}
    defaults: { _controller: VaeBaseBundle:Formation:detail , _locale: fr }
    requirements:
        _locale:  fr|en
