parameters:
#    vae_base.example.class: Vae\BaseBundle\Example

services:
#    vae_base.example:
#        class: %vae_base.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
